# VRL tag prefix -> codebook column specs, built against data/vrl_cache/tags.json after
# VRL's 2026 retag. Prefixes are token-anchored ("UOCAVA" hits "UOCAVAFcltt", not
# "PrcsDlvryUOCAVAFclt"); "*" means any tag in the group.

escape_tag <- function(x) gsub("([][{}()+*^$|\\\\?.])", "\\\\\\1", x)

tag_hit <- function(col, prefixes) {
  if (identical(prefixes, "*")) return(!is.na(col) & str_length(col) > 0)
  pat <- str_c("(^|, )(", str_c(escape_tag(prefixes), collapse = "|"), ")")
  !is.na(col) & str_detect(col, pat)
}

# Prefixes matching no bill at all usually mean VRL renamed its tags again.
build_topic_dummies <- function(df, spec, check = TRUE) {
  dead <- character(0)
  for (col in names(spec)) {
    hit <- rep(FALSE, nrow(df))
    for (g in names(spec[[col]])) {
      if (!g %in% names(df)) { dead <- c(dead, str_c(g, " (group missing)")); next }
      prefixes <- spec[[col]][[g]]
      hit <- hit | tag_hit(df[[g]], prefixes)
      if (check && !identical(prefixes, "*")) {
        for (p in prefixes) if (!any(tag_hit(df[[g]], p))) dead <- c(dead, str_c(g, ":", p))
      }
    }
    df[[col]] <- as.integer(hit)
  }
  if (check && length(dead) > 0) {
    message(sprintf("VRL tag check: %i prefixes matched no bills (retired or renamed tags): %s",
                    length(unique(dead)), str_c(unique(dead), collapse = ", ")))
  }
  df
}

vrl_topic_spec <- list(
  AVAPPL = list(`21AbsenteeVtg` = c("App", "Applc"),
                `21IncrcrtdVtng` = c("MailApp"),
                `21VoterID` = c("MailApp")),
  AVBDIS = list(`21AbsenteeVtg` = c("BlltDlvr", "Dlvry"),
                `21VBMElections` = c("BlltDlvr", "PrcsDlvry"),
                `21IncrcrtdVtng` = c("MailBlltDlvry")),
  AVBRET = list(`21AbsenteeVtg` = c("BlltRtrnVrfctnCure", "RplcmntBlltRules"),
                `21BlltRtrnVfctnCure` = c("ApplcbltyAbsntVtng", "BlltRtrn", "Rtrn", "UOCAVA", "VtrReq",
                                          "Vrfctn", "SgntrMtch", "Wtnss", "VrfCntSgntr", "RsdntlFacilities",
                                          "Cmpltn3rdPrty"),
                `21VBMElections` = c("BlltRtrnVrfctnCure", "RplcmntBlltRules"),
                `21IncrcrtdVtng` = c("MailBlltRtrn", "MailNtryWtnss"),
                `21VoterID` = c("MailBlltRtrn")),
  AVDLIN = list(`21AbsenteeVtg` = c("AppDdln"),
                `21BlltRtrnVfctnCure` = c("BlltRtrnDdln", "RtrnDdln")),
  AVELIG = list(`21AbsenteeVtg` = c("Elgbl"),
                `21IncrcrtdVtng` = c("MailElgblty")),
  AVMIOV = list(`21AbsenteeVtg` = c("UOCAVA", "UOCVAVA"),
                `21BlltRtrnVfctnCure` = c("UOCAVA"),
                `21VBMElections` = c("UOCAVA", "PrcsDlvryUOCAVA"),
                `21VtrRgstrn` = c("UOCAV")),
  AVNOEX = list(`21AbsenteeVtg` = c("ElgblElmntExcs", "ElgblImpsExcs", "ElgblNoExcsVtng")),
  AVEVIP = list(`21AbsenteeVtg` = c("InPrsnWthExcs", "VtInPrsAftrBlt"),
                `21InPrsnVtng` = c("ApplcblApplsErlyVtng"),
                `21ErlyVtngAvlblty` = "*"),
  AVMISC = list(`21AbsenteeVtg` = c("Other", "RsdntlFacilities", "EmrgVtng", "ThrdPty", "Incrc", "IncarceratedVoting"),
                `21VBMElections` = c("Other"),
                `21IncrcrtdVtng` = c("MailEmrgRqst")),
  AVPERM = list(`21PAVL` = "*",
                `21AbsenteeVtg` = c("ApplcNmbrElx")),
  BACURE = list(`21BlltRtrnVfctnCure` = c("NtcCr"),
                `21IncrcrtdVtng` = c("MailNotcCure")),
  MAILVO = list(`21BlltRtrnVfctnCure` = c("ApplcbltyVBMElctn"),
                `21VBMElections` = "*",
                `21AbsenteeVtg` = c("ElgblElmntUnv")),
  VTDROP = list(`21BlltRtrnVfctnCure` = c("BlltRtrnDOL", "RtrnDrpBx")),
  VOTSEC = list(`21BlltRtrnVfctnCure` = c("BlltRtrnDOLDrpBxScty", "RtrnDrpBxScrty")),
  INVOTE = list(`21BlltRtrnVfctnCure` = c("OnlnVtng"),
                `21AbsenteeVtg` = c("BlltDlvrOnln")),

  ELAUTH = list(`21ShftInElctnAthrty` = "*",
                `21IntrfrncElctnAdmin` = c("PowerGrabLegislature", "StiflingEmrgncyPwrs", "IntrfrncMgmtLitigatn",
                                           "ElxnRvw", "PnlzOffclLawfulPrctc", "BfrctnSttFdrlElx",
                                           "PrtsnAptmntElxnOffcl", "UnjstfdBrdnsOnOffcls", "UsurpngSttElxnAdmin",
                                           "IntrfrncCrtfctnRslts", "IntrfrncPrsdntlElctr", "IntrfrncLocalAmdmins",
                                           "IntrfrncOther"),
                `21EmergingIssues` = c("ShiftsElctnAuthority", "IntrfrncPrtct")),
  ELCOST = list(`21IntrfrncElctnAdmin` = c("RstrctGrantMoney")),
  EMEDIS = list(`21AbsenteeVtg` = c("EmrgVtng"),
                `21ShftInElctnAthrty` = c("IssueEmrgncyAuthrty"),
                `21IntrfrncElctnAdmin` = c("StiflingEmrgncyPwrs"),
                `21COVIDSttsEmrgncy` = "*",
                `21ElctnDyVtngSts` = c("LctnEmrgClsrRlct"),
                `21ErlyVtngAvlblty` = c("LctnEmrgClsrRlct"),
                `21IncrcrtdVtng` = c("MailEmrgRqst")),
  EOLOCA = list(`21ElctnCrms` = c("ApplcblElctnOffcl", "OtcmElxOffcl"),
                `21BlltRtrnVfctnCure` = c("VrfCntSgntrTraining"),
                `21ShftInElctnAthrty` = c("PwrGainLocalOffcls", "PwrLossLocalOffcls", "IssueOvrstLoclOffcls", "OffclSlct"),
                `21IntrfrncElctnAdmin` = c("IntrfrncLocalAmdmins", "Pnlz", "RskVoterWrkrIntmdtn", "PrtsnAptmntElxnOffcl",
                                           "UnjstfdBrdnsOnOffcls", "RstrctGrantMoney", "PrhbtUseTabulators"),
                `21EmergingIssues` = c("ElxnWrkrPrtctns")),
  EOSTWD = list(`21ShftInElctnAthrty` = c("PwrGainChfElctnOffcl", "PwrLossChfElctnOffcl", "PwrGainStateBoard",
                                          "PwrLossStateBoard", "PwrGainOthrOffcl", "PwrLossOthrOffcl",
                                          "PwrGainAttrnyGeneral", "PwrLossAttrnyGeneral", "PwrGainGovernor",
                                          "PwrLossGovernor", "OffclSlct"),
                `21IntrfrncElctnAdmin` = c("UsurpngSttElxnAdmin", "PnlzJobPrfrmnc", "StiflingEmrgncyPwrs",
                                           "IntrfrncMgmtLitigatn", "ElxnRvw", "PnlzOffclLawfulPrctc",
                                           "BfrctnSttFdrlElx", "PrtsnAptmntElxnOffcl", "UnjstfdBrdnsOnOffcls"),
                `21EmergingIssues` = c("ElxnWrkrPrtctns")),
  PWCOMP = list(`21InPrsnVtng` = c("PllWrkCmpstn", "PllWrkrCmpstn")),
  PWMISC = list(`21InPrsnVtng` = c("PllWrk"),
                `21IntrfrncElctnAdmin` = c("RskVoterWrkrIntmdtn"),
                `21EmergingIssues` = c("ElxnWrkrPrtctns"),
                `21VtrRgstrn` = c("CnfdntElxnWrkr")),
  PWQUAL = list(`21InPrsnVtng` = c("PllWrkQlfctn", "PllWrkRcrtmt")),
  REGLST = list(`21ShftInElctnAthrty` = c("IssueVoterListMntnc"),
                `21IntrfrncElctnAdmin` = c("PnlzListMntncInfrctn"),
                `21VtrLstMntncPrgs` = "*"),

  AUDITS = list(`21EmergingIssues` = c("Audits")),
  CRIMES = list(`21ElctnCrms` = "*",
                `21ShftInElctnAthrty` = c("IssueRprtInvstgEnfrc"),
                `21IntrfrncElctnAdmin` = c("InvstPrsctPrprtdCrms")),
  DATART = list(`21AbsenteeVtg` = c("BlltTrckng"),
                `21BlltRtrnVfctnCure` = c("BlltTrckng", "Trck"),
                `21Rdstrctng` = c("CrtrDataUse"),
                `21VtrLstMntncPrgs` = c("ChngPrcssDataSrcs"),
                `21VtngRstrtn` = c("PrcssDataShrngAgncs"),
                `21VtrRgstrn` = c("LstPblcAccs", "VtrLstPblcAccssOthr")),
  REPRES = list(`21ShftInElctnAthrty` = c("IssueElctnRslts"),
                `21IntrfrncElctnAdmin` = c("IntrfrncCrtfctnRslts"),
                `21EmergingIssues` = c("RvwCrtfd2020ElctRslt", "Cnvssng", "CrtfctnMnstrl")),
  VCOUNT = list(`21BlltRtrnVfctnCure` = c("VrfCntGrndsRj", "VrfCntObsrvr", "VrfCntTmln", "Tbltn",
                                          "VrfctnStrt", "VrfctnFnsh"),
                `21IntrfrncElctnAdmin` = c("PrhbtUseTabulators"),
                `21EmergingIssues` = c("Cnvssng")),
  VOTAST = list(`21ElctnCrms` = c("ApplcblThrdPrty", "OtcmAsstVtrs"),
                `21AbsenteeVtg` = c("AccsDsblty", "AcsblPhysDisablty", "AcsblThrdPrtyAsstnc", "ThrdPty"),
                `21BlltRtrnVfctnCure` = c("Acsbl3dPtyAsstBltCmp", "AcsblPhysDisablty", "AccsPhysDsbl",
                                          "Cmpltn3rdPrty", "BlltRtrnThrdPrty"),
                `21VtrRgstrn` = c("AcsblPhysDisablty", "ApplAccsPD"),
                `21InPrsnVtng` = c("AcsblPhysDisablty", "AcsblThdPtyAsstnce"),
                `21VBMElections` = c("AcsblPhysDisablty", "AcsblThirdPrtyAsst", "PrcsDsbltyAcsbl"),
                `21ErlyVtngAvlblty` = c("LctnAccsbltyRqrmnts", "LctnAcsbl"),
                `21ElctnDyVtngSts` = c("LctnAccsbltyRqrmnts"),
                `21VoterID` = c("ApplcbltyThrdPrtyRtr")),
  VTRCHA = list(`21BlltRtrnVfctnCure` = c("VrfCntBlltChllg", "VrfctnChllng"),
                `21InPrsnVtng` = c("Chllng")),

  LNGACC = list(`21AbsenteeVtg` = c("AcsblLanguage", "AccsLngg"),
                `21BlltRtrnVfctnCure` = c("AcsblLanguage", "AccsLng"),
                `21InPrsnVtng` = c("AcsblLanguage"),
                `21VtrRgstrn` = c("AcsblLanguage", "ApplAccsLng"),
                `21VBMElections` = c("AcsblLanguage", "PrcsLngngAcs")),
  POLWAT = list(`21ElctnCrms` = c("ApplcblPollWtchrs"),
                `21IntrfrncElctnAdmin` = c("PnlzOvsghtPollWtchrs"),
                `21InPrsnVtng` = c("PllWtchr"),
                `21BlltRtrnVfctnCure` = c("VrfCntObsrvr", "RtrnDrpBxScrtyObsrvr")),
  PPACES = list(`21InPrsnVtng` = c("AcsblPhysDisablty"),
                `21ErlyVtngAvlblty` = c("LctnAccsbltyRqrmnts", "LctnAcsbl"),
                `21ElctnDyVtngSts` = c("LctnAccsbltyRqrmnts")),
  PPLOCA = list(`21ErlyVtngAvlblty` = c("Lctn"),
                `21ElctnDyVtngSts` = c("Lctn", "Other", "Prcnct", "VtCtr"),
                `21SDR` = c("LctnChng")),
  PPVCEN = list(`21ElctnDyVtngSts` = c("VtCtr"),
                `21ErlyVtngAvlblty` = c("LctnHghCpctyVtCntr"),
                `21VBMElections` = c("VoteCenterRqrmnts")),
  PPVHRS = list(`21ElctnDyVtngSts` = c("VtHrs")),
  PREDEF = list(`21ElctnDyVtngSts` = c("PrcnctMp", "PrcnctBsd")),
  PROVOT = list(`21InPrsnVtng` = c("PrvsnlVtng"),
                `21SDR` = c("VrfctnRqrCstPrvBllt"),
                `21VoterID` = c("AltsPrvBlltChngPrcss", "InPrsnCrtRqstOnlyPrvsnlNoID")),
  VEDINF = list(`21ElctnDyVtngSts` = c("LctnVoterEducation"),
                `21ErlyVtngAvlblty` = c("LctnVtrEdctn", "VoterEducation"),
                `21IncrcrtdVtng` = c("VoterEducation"),
                `21VtngRstrtn` = c("PrcssPrvdRstRegInfo")),

  VOTRID = list(`21AbsenteeVtg` = c("AppRqID", "ApplcRqrCpyID", "ApplcRqrIDNmbr"),
                `21BlltRtrnVfctnCure` = c("BlltRtrnInPrsnIDRqrs", "RtrnInPrsnIDRqr", "VtrReqID", "VrfctnIDNmbr",
                                          "VrfctnDocRqrmnt"),
                `21SDR` = c("PrfID"),
                `21InPrsnVtng` = c("VtrRqrmntID"),
                `21VoterID` = "*",
                `21IncrcrtdVtng` = c("VtIDRqr")),
  VOTMQU = list(`21VtrRgstrn` = c("VtrRqr", "ElgblLngthRsdnc", "ElgblRsdncOthr", "ElgblMntl", "ApplRqrDocPOC"),
                `21PrfCtznshp` = "*",
                `21AVR` = c("CrtPrfCtzn", "MdfyPrfCtzn", "ChngREALIDCtznshpPrf"),
                `21VtrLstMntncPrgs` = c("RsnRmvlCtznshpStts", "RsnRmvlMntlIncpcty")),

  REGAGY = list(`21VtrRgstrn` = c("RegAgncy", "AsstAgnc"),
                `21IncrcrtdVtng` = c("RgstrJlPrsnRgstAgncy")),
  REGAPP = list(`21VtrRgstrn` = c("FrmCntntDsgn", "ApplRqr", "ApplAccs"),
                `21IncrcrtdVtng` = c("RgstrFrm")),
  REGATO = list(`21AVR` = "*"),
  REGDRV = list(`21VtrRgstrn` = c("RegDrv", "Drv3rdPty")),
  REGDTE = list(`21VtrRgstrn` = c("Ddln", "ApplDdln")),
  REGEDY = list(`21SDR` = "*"),
  REGELE = list(`21VtrRgstrn` = c("OVR", "ApplOnln")),
  REGMSC = list(`21VtrRgstrn` = c("AddrssCnfdntltyPrgms", "Cnfdnt", "Other", "ElgblRsdncOthr", "ElgblMntl", "AsstOtrch"),
                `21IncrcrtdVtng` = c("RgstrPrcss", "RgstrRsdncyRls")),
  REGPRE = list(`21VtrRgstrn` = c("PreRgstrMinor", "ElgblAgePrRg"),
                `21VtngRstrtn` = c("PrcssPreRgstrn")),
  REGSDL = list(`21VtrRgstrn` = c("RulesSaleDstrbVtrLst", "LstPblcAccs", "VtrLstPblcAccssOthr")),
  VOTFVR = list(`21AbsenteeVtg` = c("IncarceratedVoting", "Incrc"),
                `21BlltRtrnVfctnCure` = c("IncarceratedVoting", "Incrc"),
                `21VBMElections` = c("IncarceratedVoting", "PrcsDlvryIncrc"),
                `21ErlyVtngAvlblty` = c("IncarceratedVoting"),
                `21VtngRstrtn` = "*",
                `21IncrcrtdVtng` = "*",
                `21VtrRgstrn` = c("AsstOtrchFrmrInc", "AsstOtrchIncCtz"),
                `21VtrLstMntncPrgs` = c("RsnRmvlFlnyCnvctn", "RsnRmvlNonFlnyCvctn")),

  PRIMIS = list(`21VtrRgstrn` = c("PrmryVtngMinor", "ApplDdlnUpdt")),
  REDIST = list(`21Rdstrctng` = "*")
)

# Names are load-bearing downstream, including the two that keep the "21" prefix.
vrl_general_cols <- c(
  GENERAL_InPrsnVtng = "21InPrsnVtng", GENERAL_AbsenteeVtg = "21AbsenteeVtg", GENERAL_AVR = "21AVR",
  GENERAL_ElctnCrms = "21ElctnCrms", GENERAL_BlltRtrnVfctnCure = "21BlltRtrnVfctnCure",
  GENERAL_ShftInElctnAthrty = "21ShftInElctnAthrty", GENERAL_IntrfrncElctnAdmin = "21IntrfrncElctnAdmin",
  GENERAL_SDR = "21SDR", GENERAL_PAVL = "21PAVL", GENERAL_VtrRgstrn = "21VtrRgstrn",
  GENERAL_VBMElections = "21VBMElections", GENERAL_VoterID = "21VoterID",
  GENERAL_VtrLstMntncPrgs = "21VtrLstMntncPrgs", GENERAL_ElctnDyVtngSts = "21ElctnDyVtngSts",
  GENERAL_ErlyVtngAvlblty = "21ErlyVtngAvlblty", GENERAL_COVIDSttsEmrgncy = "21COVIDSttsEmrgncy",
  GENERAL_EmergingIssues = "21EmergingIssues", GENERAL_VtngRstrtn = "21VtngRstrtn",
  GENERAL_IncrcrtdVtng = "21IncrcrtdVtng", GENERAL_21Rdstrctng = "21Rdstrctng",
  GENERAL_21PrfCtznshp = "21PrfCtznshp"
)

# Expansive/restrictive direction follows Loffredo JMP Appendix C.2.
vrl_process_spec <- list(
  RESTRICT_AVVBM_SHRTAPP = list(`21AbsenteeVtg` = c("AppDdlnErlr")),
  RESTRICT_AVVBM_SHRTSUB = list(`21AbsenteeVtg` = c("BlltRtrnDdlnEarlier"),
                                `21BlltRtrnVfctnCure` = c("BlltRtrnDdlnEarlier", "RtrnDdlnElmntGrcPrd")),
  RESTRICT_AVVBM_ELIGIB = list(`21AbsenteeVtg` = c("ElgblExcsAccptNrrw", "ElgblImpsExcs", "ElgblElmntUnv",
                                                   "ElgblNoExcsVtngElmnt", "ApplcNmbrElxRdcSnglElx",
                                                   "ApplcNmbrElxElmntPAVL"),
                               `21PAVL` = c("RmvlFrmLstMksEsr", "AppDdlnErlr", "AvlbltyBOCrtnVoters", "AvlbltyEliminates",
                                            "AvlbltyProhibits", "AvlbltyRestricts", "PrmntLstAppElmtRstr",
                                            "ApplcElmnt", "ApplcPrhbt", "ApplcMdfyRstrct"),
                               `21VBMElections` = c("AvlEliminatesVBM", "AvlbPrhbt", "AvlProhibitsSmAllVBM",
                                                    "AvlElxAllwRqrVBMNrrw", "AvlJdxAllwRqrVBMNrrw")),
  RESTRICT_AVVBM_SNDAPP = list(`21AbsenteeVtg` = c("AppMailedAutoProhbts", "ApplcDstrbtOffcl",
                                                   "ApplcDstrbt3PtyRstrct", "ApplcDstrbt3PtyPrhbPrfll")),
  RESTRICT_AVVBM_SNDBLT = list(`21AbsenteeVtg` = c("AppMailedAutoProhbts", "ElgblElmntUnv"),
                               `21VBMElections` = c("AvlEliminatesVBM", "AvlbPrhbt", "AvlProhibitsSmAllVBM")),
  RESTRICT_AVVBM_LIMAST = list(`21BlltRtrnVfctnCure` = c("BlltRtrnThrdPrtyRstr", "Cmpltn3rdPrtyRstrct"),
                               `21AbsenteeVtg` = c("ThrdPtyRstrc")),
  RESTRICT_AVVBM_LIMCUR = list(`21BlltRtrnVfctnCure` = c("NtcCrCrblDfctRstrLst", "NtcCrDdlnMvsEarlier", "NtcCrMthdsRstrcts",
                                                         "NtcCrElmntPrcss", "NtcCrNtfctnRcvsLtr", "NtcCrMdfNtcMthdLmt")),
  RESTRICT_AVVBM_SIGREQ = list(`21BlltRtrnVfctnCure` = c("VrfCntSgntrCrt", "SgntrMtchVrfMdfTghtn", "VrfctnWtnsNtryRqrCrt",
                                                         "WtnssNtryVrfMdfTghtn", "VrfctnDocRqrmntCrt",
                                                         "VrfctnDocRqrmntMdfTghtn", "VrfctnOthrTghtn"),
                               `21AbsenteeVtg` = c("ApplcRqrSgntrMtchCrt", "ApplcRqrSgntrMtchTghtn",
                                                   "ApplcRqrWtnssNtryCrt", "ApplcRqrWtnssNtryTghtn")),
  RESTRICT_DROPBOX = list(`21BlltRtrnVfctnCure` = c("BlltRtrnDOLAvlRstrct", "RtrnDrpBxAthrzPrhbt", "RtrnDrpBxDyHrOprtRstrct",
                                                    "RtrnDrpBxLctnRstrct", "RtrnDrpBxNmbrDcrs")),
  RESTRICT_VTRID = list(`21AbsenteeVtg` = c("AppRqIDCrtExpnd", "ApplcRqrCpyIDCrt", "ApplcRqrCpyIDTghtn",
                                            "ApplcRqrIDNmbrCrt", "ApplcRqrIDNmbrTghtn"),
                        `21BlltRtrnVfctnCure` = c("RtrnInPrsnIDRqrCrt", "RtrnInPrsnIDRqrTghtn", "VrfctnIDNmbrRqrmntCrt",
                                                  "VrfctnIDNmbrRqrmntMdfTghtn", "VtrReqIDCrtExpnd"),
                        `21InPrsnVtng` = c("VtrRqrmntIDCrtExpnd"),
                        `21VoterID` = c("AltsElmntsRstrcts", "ApplcbltyAbsntVtng", "ApplcbltyErlyVtng",
                                        "ApplcbltyElctnDyVtng", "BOPhotoIDRqrd", "IDRqrmntCrts",
                                        "FreeIDElmntRstrct", "TypeAccptdElmnts",
                                        "InPrsnCrt", "InPrsnMdfExcptnElmnt", "InPrsnMdfExcptnLmt",
                                        "InPrsnMdfFrmsIDRstrcts", "MailAppCpyIDCrt", "MailAppIDNmbrCrt",
                                        "MailAppOthrRqrmntCrt", "MailBlltRtrnCpyIDCrt", "MailBlltRtrnIDNmbrCrt",
                                        "MailBlltRtrnOthrRqrmntCrt", "MailExcptElmnt", "MailExcptLmts",
                                        "MailMdfFrmsIDRstrcts"),
                        `21SDR` = c("PrfRsdncCrtExpndRqr", "PrfIDCrtExpndRqPht", "PrfIDCrtExpndRqNnPht"),
                        `21IncrcrtdVtng` = c("VtIDRqrPrvdsCmplntID")),
  RESTRICT_VTRREG_EXPREM = list(`21VtrLstMntncPrgs` = c("RsnRmvl")),
  RESTRICT_VTRREG_DIFICT = list(`21AVR` = c("ChngPrtcptAgncyRmvs", "ChngREALIDCtznshpPrf", "EliminatesAVR", "ElmntsAllAgncs",
                                            "CrtPrfCtznRealIDRqrs", "MdfyPrfCtznRealIDRqrs", "ChngOptOutTmngErlr"),
                                `21IncrcrtdVtng` = c("PrcssPrfRgCrtStrngRq", "RgstrFrmAvlbltyRstrc", "RgstrPrcssRstrct"),
                                `21VtngRstrtn` = c("PrcssPrfRgCrtStrngRq"),
                                `21VtrRgstrn` = c("DdlnNewRgstrnErlr", "DdlnUpdtRgstrnErlr", "PreRgstrMinorElmn",
                                                  "RegAgncyRmvsAgncy", "RegDrvAsstncPrhbt", "Drv3rdPtyRstrcTghtn",
                                                  "ApplRqrBrdnIncrs", "ApplRqrDocOthrCrt", "ApplRqrDocOthrTtns",
                                                  "ApplRqrDocPOCCrts", "ApplRqrDocPOCTtns", "ApplRqrDocRsdPrfCrt",
                                                  "ApplRqrDocRsdPrfTtn", "ApplRqrIDCrts", "ApplRqrIDTtns",
                                                  "ElgblLngthRsdncEstb", "ElgblLngthRsdncTtns", "ApplOnlnElmn",
                                                  "ApplOnlnChngCrtDMV", "AsstAgncAIEndAgncRqr", "AsstAgncAIElmntPtntAgnc",
                                                  "AsstOtrchCllgRstrc", "AsstOtrchFrmrIncRstrc", "AsstOtrchFrrmRstrc",
                                                  "AsstOtrchHSRstrc", "AsstOtrchIncCtzRstrc", "AsstOtrchOthrElmn",
                                                  "AsstOtrchRntrRstrc", "ElgblAgePrRgOldr", "ApplAccsLngRdc", "ApplAccsPDRdc"),
                                `21PrfCtznshp` = c("Creates_", "Changes_Requirement_>_Tightens")),
  RESTRICT_VTTREG_NOSDYR = list(`21SDR` = c("AvlEVElmntRstrct", "AvlElctDyElmntRstrct")),
  RESTRICT_IPV_PPLOCA = list(`21ElctnDyVtngSts` = c("PrcnctBsdPllPlcElmnt", "LctnNmbrRqrdDcrs", "VtCtrEliminates", "VtHrsRdcs",
                                                    "VtCtrElxRqrAllwRstrc", "VtCtrJdxRqrAllwRstrc")),
  RESTRICT_ERLVTG_LIMIT = list(`21ErlyVtngAvlblty` = c("TmngVtngHoursRdcs", "TmngHrsMndtryRdc", "TmngHrsDscrtnryRdc",
                                                       "TmngSunVtngElmntNrrw", "TmngSatVtngElmntNrrw",
                                                       "TmngWkndSndyElmnt", "TmngWkndSndyLmt", "TmngWkndStrdyElmnt",
                                                       "TmngWkndStrdyLmt", "TmngLstDyMvsErlr", "TmngFrstDyMvsLtr",
                                                       "TmngEVPrdShrtns", "AvlbEliminates", "AvlbRestricts",
                                                       "LctnNmbrMndtryDcrss", "LctnNmbrDscrtnryDcrss",
                                                       "LctnAcsblCrbsdRstrct", "LctnAcsblRsdntFcltyLmt")),
  RESTRICT_EOS_WEAKEN = list(`21IntrfrncElctnAdmin` = c("BfrctnSttFdrlElx", "PrtsnAptmntElxnOffcl", "IntrfrncLocalAmdmins",
                                                        "IntrfrncMgmtLitigatn", "IntrfrncCrtfctnRslts", "IntrfrncPrsdntlElctr",
                                                        "IntrfrncOther", "PnlzJobPrfrmnc", "PnlzListMntncInfrctn",
                                                        "PnlzOffclLawfulPrctc", "PnlzOvsghtPollWtchrs", "PowerGrabLegislature",
                                                        "ElxnRvw", "RskVoterWrkrIntmdtn", "StiflingEmrgncyPwrs",
                                                        "UnjstfdBrdnsOnOffcls", "PrhbtUseTabulators", "RstrctGrantMoney",
                                                        "UsurpngSttElxnAdmin")),
  RESTRICT_CRIMES = list(`21ElctnCrms` = c("ApplcblThrdPrty", "ApplcblVoters", "CivilPenaltiesCrts", "CivilPenaltiesExpnds",
                                           "FelonyCreates", "FelonyExpands", "MisdemeanorCreates", "MisdemeanorExpnds",
                                           "CrtsExpnds", "zCrtsExpnds", "OtcmAsstVtrsIncrsCrm", "OtcmVotersIncrsCrm",
                                           "OtcmElxOffclIncrsCrm", "PnltyIncrsSvrtyPnlty")),

  EXPAND_ABVVBM_ESYMVT = list(`21ErlyVtngAvlblty` = c("AvlbBOInPrsnNoExc"),
                              `21PAVL` = c("AppAddRgstrnApp", "AppDdlnLtr", "AvlbltyCreates", "AvlbltyBOAllVoters",
                                           "AvlbltyExpands", "PrmntLstAppCrtExpnd", "AvlbCrts", "AvlbMdfyExpnd",
                                           "ApplcCrt", "ApplcMdfyExpnd", "EnrllOllnExpndAccss", "RmvlFrmLstMksHrdr"),
                              `21AbsenteeVtg` = c("AppMailedAutoAllVtr", "AppMailedAutoCrtnVtr", "AppOnlnCrt", "ApplcOnlnPrtlCrt",
                                                  "AppRqIDElmntRlx", "ApplcRqrCpyIDElmnt", "ApplcRqrCpyIDLsn",
                                                  "ApplcRqrIDNmbrElmnt", "ApplcRqrIDNmbrLsn", "ApplcRqrOthrLsn",
                                                  "ApplcRqrWtnssNtryElmnt", "ApplcRqrWtnssNtryLsn", "ApplcRqrSgntrMtchElmnt",
                                                  "ApplcRqrSgntrMtchLsn", "AppRqNtryWtnsElmRlx", "AppRtrnPstgPdByGov",
                                                  "ApplcCrtsPrPdPstgRqr", "ApplcDstrbt3PtyFclt", "ApplcNmbrElxMrElx",
                                                  "ApplcNmbrElxCrtPAVL", "AppDdlnLtr", "BlltDlvrOnlnAvlbl",
                                                  "BlltDlvrTmlnEarlier", "BlltDlvrInPrsPckpExp", "DlvryRplcmntFclt",
                                                  "DlvryRsdntExpnds", "ElgblExcsAccptExpnd", "ElgblElmntExcs",
                                                  "ElgblNoExcsVtngCrts", "EmrgVtngFacilitates", "InPrsnWthExcsCrtExpn",
                                                  "VtInPrsAftrBltCrtExp", "ThrdPtyFclt", "UOCVAVAFclt", "IncrcFclt"),
                              `21BlltRtrnVfctnCure` = c("BlltRtrnDdlnLater", "BlltRtrnDOLAvlExpnd", "BlltRtrnPstgPdByGov",
                                                        "RtrnDrpBxAthrzAllw", "RtrnDrpBxDyHrOprtExpnd", "RtrnDrpBxLctnExpnd",
                                                        "RtrnDrpBxNmbrIncrs", "UOCAVAFcltt", "VrfctnElmntElmnt",
                                                        "WtnssNtryVrfMdfLsns", "SgntrMtchVrfMdfLsns", "VrfCntSgntrElmnt",
                                                        "VrfctnDocRqrmntElmnt", "VrfctnDocRqrmntMdfLsns",
                                                        "VrfctnIDNmbrRqrmntElmnt", "VrfctnIDNmbrRqrmntMdfLsns",
                                                        "VrfctnOthrLsns", "RtrnInPrsnIDRqrElmnt", "RtrnInPrsnIDRqrLsns",
                                                        "TrckCrt", "TrckImprv"),
                              `21VBMElections` = c("AvlCrtVBM", "AvlElxAllwRqrVBMExpn", "AvlJdxAllwRqrVBMExpn", "AvlPilotProject",
                                                   "AvlbCrts", "AvlbMdfyElxTypExpnd", "AvlbMdfyJdx", "PrcsDlvryAltAddFclt",
                                                   "PrcsDlvryIncrcFclt", "PrcsDlvryRplcFclt", "PrcsDlvryRsdntExpnd",
                                                   "PrcsDlvryUOCAVAFclt", "PrcsInPrsnFclt"),
                              `21IncrcrtdVtng` = c("MailAppAvlbltyExpnd", "MailAppPrcssFcltates", "MailBlltDlvryFcltate",
                                                   "MailBlltRtrnFcltates", "MailElgbltyCrtExp", "MailEmrgRqstCrtExpnd",
                                                   "MailNtryWtnssRqFcltt")),
  EXPAND_ABVVBM_ESYBCP = list(`21BlltRtrnVfctnCure` = c("NtcCrCrblDfctExpnLst", "NtcCrDdlnMvsLater", "NtcCrMthdsExpnds",
                                                        "NtcCrNtfctnRcvsErlr", "NtcCrCrtsNewPrcss", "NtcCrDfctsExpndExstGrnd",
                                                        "NtcCrDfctsNwGrndRjctn", "NtcCrMdfNtcMthdExpnd"),
                              `21IncrcrtdVtng` = c("MailNotcCureFcltates")),
  EXPAND_ABVVBM_MBAST = list(`21BlltRtrnVfctnCure` = c("BlltRtrnThrdPrtyExpd", "Acsbl3dPtyAsstBltCmp", "Cmpltn3rdPrtyFcltt",
                                                       "AccsPhysDsblExpndAccmdtn", "AccsLngExpndAccmdtn"),
                             `21VBMElections` = c("AcsblThirdPrtyAsst", "PrcsDsbltyAcsblExpnd", "PrcsLngngAcsExpnd"),
                             `21AbsenteeVtg` = c("ThrdPtyFclt", "AccsDsbltyExpnd", "AccsLnggExpnd")),
  EXPAND_ABVVBM_INTVTG = list(`21BlltRtrnVfctnCure` = c("OnlnVtngAvlblAllVtrs", "OnlnVtngAvlblSmVtrs")),
  EXPAND_VTRID = list(`21VoterID` = c("AltsCrtsExpnds", "BOPhotoIDNotRqrd", "FreeIDCrtsExpnds", "IDNmbrRqrmntRpls", "TypeAccptdAdds",
                                      "InPrsnElmnt", "InPrsnMdfExcptnEstbl", "InPrsnMdfExcptnExpnd", "InPrsnMdfFrmsIDExpnd",
                                      "MailAppCpyIDElmnt", "MailAppIDNmbrElmnt", "MailAppOthrRqrmntElmnt",
                                      "MailBlltRtrnCpyIDElmnt", "MailBlltRtrnIDNmbrElmnt", "MailBlltRtrnOthrRqrElmnt",
                                      "MailExcptEstblsh", "MailExcptExpnd", "MailMdfFrmsIDExpnd"),
                      `21InPrsnVtng` = c("VtrRqrmntIDElmntRlx"),
                      `21AbsenteeVtg` = c("AppRqIDElmntRlx", "ApplcRqrCpyIDElmnt", "ApplcRqrCpyIDLsn",
                                          "ApplcRqrIDNmbrElmnt", "ApplcRqrIDNmbrLsn"),
                      `21BlltRtrnVfctnCure` = c("VtrReqIDElmntRlx", "RtrnInPrsnIDRqrElmnt", "RtrnInPrsnIDRqrLsns",
                                                "VrfctnIDNmbrRqrmntElmnt", "VrfctnIDNmbrRqrmntMdfLsns"),
                      `21SDR` = c("PrfIDCrtExpndRqNnPht", "PrfIDNewSDRNotRqrd", "PrfIDElmntRlxRqrmnts"),
                      `21IncrcrtdVtng` = c("VtIDRqrAddJlPrsnID", "VtIDRqrExmptIDRqr")),
  EXPAND_VTRREG_REGESY = list(`21VtrRgstrn` = c("RegDrvAsstncAuthrzs", "Drv3rdPtyFclttsLsns", "RegAgncyAddAgncy",
                                                "AsstAgncAIAdd", "AsstAgncFrmExpnd", "AsstOtrchCllgExpnd",
                                                "AsstOtrchFrmrIncExpnd", "AsstOtrchFrrmExpnd", "AsstOtrchHSExpnd",
                                                "AsstOtrchIncCtzExpnd", "AsstOtrchOthrCrt", "AsstOtrchRntrExp",
                                                "PreRgstrMinorCrt", "ElgblAgePrRgYngr", "DdlnUpdtRgstrnLtr",
                                                "DdlnNewRgstrnLtr", "ApplRqrBrdnRdcs", "ApplRqrDocOthrElmnt",
                                                "ApplRqrDocOthrLsns", "ApplRqrDocPOCElmn", "ApplRqrDocPOCLsns",
                                                "ApplRqrDocRsdPrfElm", "ApplRqrDocRsdPrfLsn", "ApplRqrIDElmn",
                                                "ApplRqrIDLsns", "ApplOnlnCrt", "ApplOnlnChngElmnDMV",
                                                "ElgblLngthRsdncElmnt", "ElgblLngthRsdncLsns", "ApplAccsLngExpnd",
                                                "ApplAccsPDExpnd", "PrmryVtngMinorCrts"),
                              `21AVR` = c("CrtAVR", "ChngPrtcptAgncyAdds", "CrtAgnc", "MdfyAgncExpnd", "ChngOptOutTmngLtr",
                                          "MdfyPrfCtznRealIDRmvs", "MdfyCdfyLw"),
                              `21IncrcrtdVtng` = c("RgstrPrcssFcltate", "RgstrFrmAvlbltyExpnd", "RgstrJlPrsnRgstAgncy"),
                              `21PrfCtznshp` = c("Eliminates_Requirement", "Changes_Requirement_>_Loosens")),
  EXPAND_VTRREG_SMEDAY = list(`21SDR` = c("PrfRsdncNewSDRNotRqr", "LngthRsdncRqElmShrtn", "AvlElctDyCrtExpnd", "AvlEVCrtsExpnds",
                                          "PrfRsdncElmntRlxRqr", "VrfctnAllwCstRegBllt")),
  EXPAND_DISABLE = list(`21VBMElections` = c("AcsblPhysDisablty", "PrcsDsbltyAcsblExpnd"),
                        `21VtrRgstrn` = c("AcsblPhysDisablty", "ApplAccsPDExpnd"),
                        `21BlltRtrnVfctnCure` = c("AcsblPhysDisablty", "AccsPhysDsblExpndAccmdtn"),
                        `21AbsenteeVtg` = c("AcsblPhysDisablty", "AccsDsbltyExpnd"),
                        `21InPrsnVtng` = c("AcsblPhysDisablty"),
                        `21ErlyVtngAvlblty` = c("LctnAccsbltyRqrmnts", "LctnAcsblExpnd", "LctnAcsblCrbsdExpnd"),
                        `21ElctnDyVtngSts` = c("LctnAccsbltyRqrmnts")),
  EXPAND_IPV = list(`21ElctnCrms` = c("ApplcblPollWtchrs"),
                    `21ElctnDyVtngSts` = c("VtHrsExpnds", "VtHrsChngPrcssExtnd", "VtCtrJdxRqrAllwExpnd", "VtCtrHghCpctyVtCntr",
                                           "VtCtrElxRqrAllwExpnd", "VtCtrCrts", "VtCtrBO", "LctnNmbrRqrdIncr",
                                           "PrcnctBsdPllPlcCrts", "LctnDrvThruOutdrVtng")),
  EXPAND_EARLY = list(`21ErlyVtngAvlblty` = c("TmngVtngHoursExpnds", "TmngHrsMndtryExpnd", "TmngHrsDscrtnryExpnd",
                                              "TmngSunVtngCrtExpnd", "TmngSatVtngCrtExpnd", "TmngWkndSndyEstblsh",
                                              "TmngWkndSndyExpnd", "TmngWkndStrdyEstblsh", "TmngWkndStrdyExpnd",
                                              "TmngLstDyMvsLtr", "TmngFrstDyMvsErlr", "TmngEVPrdLgnthns", "AvlbCreates",
                                              "AvlbExpndsFcilitates", "AvlbBO", "LctnNmbrMndtryIncrs",
                                              "LctnNmbrDscrtnryIncrs", "LctnAcsblExpnd", "LctnAcsblCrbsdExpnd",
                                              "LctnAcsblRsdntFcltyCrts", "LctnHghCpctyVtCntr")),
  EXPAND_LNGACS = list(`21VBMElections` = c("AcsblLanguage", "PrcsLngngAcsExpnd"),
                       `21VtrRgstrn` = c("AcsblLanguage", "ApplAccsLngExpnd"),
                       `21BlltRtrnVfctnCure` = c("AcsblLanguage", "AccsLngExpndAccmdtn"),
                       `21AbsenteeVtg` = c("AcsblLanguage", "AccsLnggExpnd"),
                       `21InPrsnVtng` = c("AcsblLanguage")),
  EXPAND_STVRA = list(`21EmergingIssues` = c("StateVtngRghtsPrtctn")),
  EXPAND_FELON_RSTVTR = list(`21VtngRstrtn` = c("BOAutoAftrIncrcrtn", "ChgMthdApp2Auto", "DsnfrnchEndAllCnvcts",
                                                "DsnfrnchCnvctsNrrws", "TmngErlrRntryPrcss", "FnclRqNrrwElmnt")),
  EXPAND_FELON_EASY = list(`21VBMElections` = c("IncarceratedVoting", "PrcsDlvryIncrcFclt"),
                           `21BlltRtrnVfctnCure` = c("IncarceratedVoting", "IncrcFcltt"),
                           `21AbsenteeVtg` = c("IncarceratedVoting", "IncrcFclt"),
                           `21ErlyVtngAvlblty` = c("IncarceratedVoting"),
                           `21IncrcrtdVtng` = c("VtIDRqrExmptIDRqr", "VtIDRqrAddJlPrsnID", "RgstrPrcssFcltate",
                                                "RgstrFrmAvlbltyExpnd", "RgstrJlPrsnRgstAgncy", "OnStCrtExpnd", "OnStBO",
                                                "MailNotcCureFcltates", "MailNtryWtnssRqFcltt", "MailEmrgRqstCrtExpnd",
                                                "MailElgbltyCrtExp", "MailBlltRtrnFcltates", "MailBlltDlvryFcltate",
                                                "MailAppPrcssFcltates", "MailAppAvlbltyExpnd"),
                           `21VtrRgstrn` = c("AsstOtrchFrmrIncExpnd", "AsstOtrchIncCtzExpnd"),
                           `21VtngRstrtn` = c("PrcssPrvdRstRegInfo", "PrcssPrfRgElmntRlxRq", "PrcssDataShrngAgncs"))
)
